api/urls.py
from django.conf.urls import url, include
from rest_framework.authtoken import views as token_views
from rest_framework import routers
from api import views

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)

urlpatterns = [
    url(r'^', include(router.urls)),
    url(r'^o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    url(r'^api-token-auth/', token_views.obtain_auth_token),
]

blog/urls.py
from django.conf.urls import url, patterns
from django.contrib.auth.decorators import login_required
from django.views.generic.base import RedirectView
from blog.views import GreetingView, BlogView, AuthorDetailView, AuthorListView, AuthorCreate, AuthorUpdate, AuthorDelete

urlpatterns = [
    url(r'^$', GreetingView.as_view()),
    url(r'^baidu/$', RedirectView.as_view(pattern_name="google"), name='baidu'),
    url(r'^google/$', RedirectView.as_view(url="http://www.google.com.hk"), name='google'),
    url(r'^authors/(?P<pk>[0-9]+)/$', AuthorDetailView.as_view(), name='author-detail'),
    url(r'^authors/$', AuthorListView.as_view(), name='author-list'),
    url(r'author/add/$', AuthorCreate.as_view(), name='author-add'),
    url(r'author/(?P<pk>[0-9]+)/$', AuthorUpdate.as_view(), name='author-update'),
    url(r'author/(?P<pk>[0-9]+)/delete/$', AuthorDelete.as_view(), name='author-delete'),
    #url(r'^$', login_required(GreetingView.as_view())),

]

newest/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from blog.views import RegisterView, RegisterDoneView, AboutView, ContactView

urlpatterns = [
    url(r'accounts/login/$', auth_views.login, name='login'),
    url(r'accounts/logout/$', auth_views.logout, name='logout'),
    url(r'^accounts/register/$', RegisterView.as_view(), name='register'),
    url(r'^accounts/register/done/$', RegisterDoneView.as_view(), name='register_done'),
    url(r'^about/$', AboutView.as_view(), name='about'),
    url(r'^contact/$', ContactView.as_view(), name='contact'),
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls')),
    url(r'^dns/', include('dns.urls')),
    url(r'^api/', include('api.urls')),
]

blog/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver
from rest_framework.authtoken.models import Token

class Blog(models.Model):
    title = models.CharField(max_length=100)
    body = models.TextField()
    timestamp = models.DateTimeField()
    owner = models.ForeignKey(User)

    class Meta:
	db_table = u'blog'

    def __unicode__(self):
	return u'%s %s' % (self.title, self.owner.username)

class Author(models.Model):
    name = models.CharField(max_length=200)
    last_accessed = models.DateTimeField()
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)

    def get_absolute_url(self):
	return reverse('author-detail', kwargs={'pk': self.pk})

@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)

blog/forms.py
from django import forms
from .models import Author

class ContactForm(forms.Form):
    contact_name = forms.CharField(required=True)
    contact_email = forms.EmailField(required=True)
    content = forms.CharField(
	required=True,
	widget=forms.Textarea
    )

    def __init__(self, *args, **kwargs):
	super(ContactForm, self).__init__(*args, **kwargs)
	self.fields['contact_name'].label = "your name:"
	self.fields['contact_email'].label = "your email:"
	self.fields['content'].label = "what do you want to say?"

class AuthorForm(forms.ModelForm):
    class Meta:
	model = Author
	fields = ['name', 'created_by', 'last_accessed']

blog/views.py
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.views.generic import View, FormView, DetailView, ListView, CreateView, UpdateView, DeleteView
from django.views.generic.base import TemplateView
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render
from django.core.urlresolvers import reverse, reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils import timezone
from django.template.loader import get_template, render_to_string
from django.template import Context
from django.core.mail import EmailMessage
from .models import Blog, Author
from .forms import ContactForm, AuthorForm
import logging
logger = logging.getLogger(__name__)

class GreetingView(LoginRequiredMixin, View):
    login_url = '/accounts/login/'
    redirect_field_name = 'next'
    greeting = "Good Day"

    def get(self, request):
        logger.warning("an error")
	return HttpResponse(self.greeting)

class RegisterView(View):
    form_class = UserCreationForm
    template_name = 'register.html'

    def get(self, request, *args, **kwargs):
        form = self.form_class()
	return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
	form = self.form_class(request.POST)
	if form.is_valid():
            form.save()
	    return HttpResponseRedirect(reverse('register_done'))
	return render(request, self.template_name, {'form': form})	

class RegisterDoneView(View):
    def get(self, request):
	return HttpResponse("success.")

class BlogView(LoginRequiredMixin, TemplateView):

    template_name = 'blog.html'

    def get_context_data(self, **kwargs):
	context = super(BlogView, self).get_context_data(**kwargs)
	context['latest_blogs'] = Blog.objects.all()[:5]
	return context 

class AboutView(TemplateView):
    template_name = 'about.html'

    def get_context_data(self, **kwargs):
	context = super(AboutView, self).get_context_data(**kwargs)
        now = timezone.localtime(timezone.now())
	if now.weekday() < 5 and 8 < now.hour < 18:
	    context['open'] = True
	else:
	    context['open'] = False
	return context

class ContactView(FormView):
    form_class = ContactForm
    template_name = 'contact.html'
    success_url = reverse_lazy('contact')

    def form_valid(self, form):
	contact_name = form.cleaned_data['contact_name']
	contact_email = form.cleaned_data['contact_email']
	form_content = form.cleaned_data['content']
	
	context = {
	    'contact_name': contact_name,
	    'contact_email': contact_email,
	    'form_content': form_content
	}
	content = render_to_string('contact_template.txt', context)
	
	email = EmailMessage(
	    'new contact',
	    content,
	    from_email='Dont reply<do_not_reply@domain.com>',
	    to=['to_email'],
	    headers = {'Reply-To': contact_email}
	)
	email.send()
	return super(ContactView, self).form_valid(form)

class AuthorDetailView(DetailView):
    queryset = Author.objects.all()
    template_name = 'blog/detail.html'

    def get_object(self):
	object = super(AuthorDetailView, self).get_object()
	object.last_accessed = timezone.now()
	object.save()
	return object

class AuthorListView(ListView):
    context_object_name = 'authors'
    queryset = Author.objects.all()
    template_name = 'blog/list.html'

class AjaxableResponseMixin(object):
    def form_invalid(self, form):
	response = super(AjaxableResponseMixin, self).form_invalid(form)
	if self.request.is_ajax():
	    return JsonResponse(form.errors, status=400)
	else:
	    return response

    def form_valid(self, form):
	response = super(AjaxableResponseMixin, self).form_valid(form)
	if self.request.is_ajax():
	    data = {
		'pk': self.object.pk,
	    }
	    return JsonResponse(data)
	else:
	    return response

class AuthorCreate(AjaxableResponseMixin, CreateView):
    model = Author
    form_class = AuthorForm

    def form_valid(self, form):
	#form.instance.created_by = self.request.user
	return super(AuthorCreate,self).form_valid(form)

class AuthorUpdate(UpdateView):
    model = Author
    form_class = AuthorForm

class AuthorDelete(DeleteView):
    model = Author
    success_url = reverse_lazy('author-list')

templates/blog/author_confirm_delete.html
{% extends 'base.html' %}
{% block title %}author delete{% endblock %}

{% block content %}
  <form action="" method="POST">
    {% csrf_token %}
    <p><label>name:</label>{{ object.id }}</p>
    <p><label>last accessed:</label>{{ object.last_accessed }}</p>
    <input type="submit" value="Delete">
  </form>
{% endblock %}

templates/blog/author_form.html
{% extends 'base.html' %}
{% block title %}author{% endblock %}

{% block header %}
  <script src="http://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script>
    $.ajaxSetup({
      data: {
	csrfmiddlewaretoken: '{{ csrf_token }}',
      }
    });

    function ajax_test() {
      $.ajax({
	type: "POST",
	url: "http://localhost:8000/blog/author/add/", 
	data: get_post_data(),
        dataType: "json",
        /*
	beforeSend: function(xhr) {
	  xhr.setRequestHeader("X-CSRFToken", get_csrf_token());
	},
	*/
	success: function(data) {
	  console.log("the result: "+data);
	}
      }); 
    }
    
    function get_csrf_token() {
      return $('input[name="csrfmiddlewaretoken"]').val()
    }

    function get_post_data() {
      console.log("get_post_data");
      var name, created_by, last_accessed;
      name = $("#id_name").val();
      created_by = $("#id_created_by").val();
      last_accessed = $("#id_last_accessed").val();
      console.log("name:"+name+";created_by:"+created_by+";last_accessed:"+last_accessed);
      return {
	"name": name,
	"created_by": created_by,
	"last_accessed": last_accessed
      }
    }

  </script>
{% endblock %}

{% block content %}
  <form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
  </form>
  <input id="ajax" type="button" value="ajax" onclick="ajax_test()">
{% endblock %}

templates/blog/detail.html
{% extends 'base.html' %}
{% block title %}blog detail{% endblock %}

{% block content %}
<p> {{ object.id }} -- {{ object.name }} -- {{ object.last_accessed }}</p>
{% endblock %}

templates/blog/list.html
{% extends 'base.html' %}
{% block title %}author list{% endblock %}

{% block content %}
{% for author in authors %}
<p>{{ author.id}}--{{ author.name }}--{{ author.last_accessed }}--{{ author.created_by }}</p>
{% endfor %}
{% endblock %}